### ISSUE TITLE
remove '.' rood tree auto created

### ISSUE THREAD

**Issue by dylancis** [metrumresearchgroup/jsTree#10]
Hi @yonicd-
I have been playing around a lot the past 24 hours with your package and I was trying to figure out how to get rid of the root folder '.' created automatically please?
![image](https://user-images.githubusercontent.com/4976433/39869553-e3b55c62-5455-11e8-92ae-a2572e136ed5.png)

I don't create this root myself not sure why it is getting added.
Many thanks, Dylan

**Comment by dylancis** [comment]
I see, thanks, do you think it could rather be an exposed argument via `jsTree()` instead? Such `dotRoot = TRUE,` something like this ?

**Comment by yonicd** [comment]
i removed that fake parent. https://github.com/metrumresearchgroup/jsTree/commit/d2b658809f037f493fe9b69f1ab724dc8a18f4f6

**Comment by dylancis** [comment]
many thanks.
