### ISSUE TITLE
plugins_api do not render tree anymore

### ISSUE THREAD

**Issue by dylancis** [metrumresearchgroup/jsTree#12]
Hi @yonicd , sorry I could test the **plugins_api** banch earlier but I upgraded this morning and this is not working anymore:
```
data(states)
data(state_bird)
#collapse columns to text (with sep "/")
nested_string <- apply(states,1,paste,collapse='/')
jsTree(nested_string)
```

![image](https://user-images.githubusercontent.com/4976433/42695509-75a7548e-86ad-11e8-9c1a-a1199d0d9cab.png)

**Comment by dylancis** [comment]
my bad - this has something to do with my own environment.
closing this one.

**Comment by yonicd** [comment]
don't use the plugins_api branch i created the R6_api branch instead. It is a better solution.

**Comment by dylancis** [comment]
thanks for this. much better :-)
