### ISSUE TITLE
please update to latest jsTree 3.3.7 - chrome presents error

### ISSUE THREAD

**Issue by obkhan** [metrumresearchgroup/jsTree#15]
jstree.min.js:6 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
(anonymous) @ jstree.min.js:6

**Comment by yonicd** [comment]
updated in branch. will move it to CRAN next week. https://github.com/metrumresearchgroup/jsTree/commit/2336b2fe8e5da751e5f25e12a723064015bf6205
