### ISSUE TITLE
how does this differ from shinyTree? 

### ISSUE THREAD

**Issue by dockstreet** [metrumresearchgroup/jsTree#2]
Hi,

Just curious is this jsTree more geared for Github repositories or is that a bonus feature? Also how does it contrast with 
https://github.com/trestletech/shinyTree?

Does it use the latest version of jsTree?

**Comment by yonicd** [comment]
shinyTree has old jsTree.js hardcoded in a shinyapp. jsTree is a standalone htmlwidget that can be used in interactive R environment. 

It works alone for local heirarchies like folder structures, or along with metrumresearchgroup/vcs can be used to navigate vcs repos like git/github/svn/bitbucket

It has the latest source js of jsTree.js

**Comment by yonicd** [comment]
closing for now
