### ISSUE TITLE
crosstalk?

### ISSUE THREAD

**Issue by dockstreet** [metrumresearchgroup/jsTree#3]
Does this support crosstalk? if so is there an example?
https://rstudio.github.io/crosstalk/

**Comment by yonicd** [comment]
I didnt put in crosstalk.js, but it has observers for shiny that can be used in conjunction with other widgets/reactive objects.

The package contains interactive examples . https://github.com/metrumresearchgroup/jsTree/tree/master/inst/examples

**Comment by yonicd** [comment]
closing for now
